package mathops

import (
	"fmt"
	ePref "github.com/MikeAustin71/errpref"
	"sync"
)

type numStrDtoMuon struct {
	lock sync.Mutex
}

// findNumStrSignificantDigitLimits
//
//	Analyzes an array of characters which constitute a number
//	string are returns the significant digits in a new instance of
//	NumStrDto.
//
//	Example
//	=======
//
//	absAllRunes  precision  signVal  Result
//
//	001236700        4         1     123.67
//	000006700        4         1       0.67
//	001230000        4         1     123.0
func (nStrDtoMuon *numStrDtoMuon) findNumStrSignificantDigitLimits(
	numSeps NumericSeparatorDto,
	absAllRunes []rune,
	precision uint,
	signVal int,
	errPrefDto *ePref.ErrPrefixDto) (NumStrDto, error) {

	nStrDtoMuon.lock.Lock()

	defer nStrDtoMuon.lock.Unlock()

	var ePrefix *ePref.ErrPrefixDto
	var err error

	ePrefix,
		err = ePref.ErrPrefixDto{}.NewFromErrPrefDto(
		errPrefDto,
		"numStrDtoMuon.findNumStrSignificantDigitLimits()",
		"")

	if err != nil {
		return NumStrDto{}, err
	}

	err = numSeps.IsValid(ePrefix.XCpy("Validating 'numSeps'").String())

	if err != nil {

		return NumStrDto{},
			&FuncReturnError{
				ErrPrefix:  ePrefix.String(),
				ReturnFunc: "err = numSeps.IsValid(ePrefix.XCpy(\"Validating 'numSeps'\").String())",
				ErrContext: "Error: Numeric Separators ('numSeps') are INVALID!",
				ErrMessage: err.Error(),
			}
	}

	lenAbsAllRunes := len(absAllRunes)

	if signVal != -1 && signVal != 1 {

		return NumStrDto{},
			&FuncReturnError{
				ErrPrefix:  ePrefix.String(),
				ReturnFunc: "",
				ErrContext: "",
				ErrMessage: "Error: Input parameter 'signVal' is INVALID!\n" +
					"signVal must be either -1 or 1\n" +
					fmt.Sprintf("signVal=%d", signVal),
			}
	}

	if lenAbsAllRunes < 1 {
		return NumStrDto{},
			&FuncReturnError{
				ErrPrefix:  ePrefix.String(),
				ReturnFunc: "",
				ErrContext: "len(absAllRunes) == 0",
				ErrMessage: "Error: Input parameter 'absAllRunes' is INVALID!\n" +
					"'absAllRunes' has ZERO length.",
			}
	}

	if precision > uint(lenAbsAllRunes) {
		return NumStrDto{},
			&FuncReturnError{
				ErrPrefix:  ePrefix.String(),
				ReturnFunc: "",
				ErrContext: "precision > uint(lenAbsAllRunes)",
				ErrMessage: "Error: Input parameter 'precision' is INVALID!\n" +
					"'precision' value is greater than length of rune array.",
			}
	}

	iPrecision := int(precision)
	firstIntIdx := -1
	lastIntIdx := -1
	lastFracIdx := -1

	isFractional := false

	if iPrecision > 0 {
		isFractional = true
	}

	lenAbsFracRunes := iPrecision

	lenAbsIntRunes := lenAbsAllRunes - lenAbsFracRunes

	for i := 0; i < lenAbsAllRunes; i++ {

		if i < lenAbsIntRunes {

			if firstIntIdx == -1 && absAllRunes[i] > '0' && absAllRunes[i] <= '9' {
				firstIntIdx = i
			}

			lastIntIdx = i
		}

		if isFractional && i >= lenAbsIntRunes && absAllRunes[i] > '0' && absAllRunes[i] <= '9' {

			lastFracIdx = i
		}

	}

	if firstIntIdx == -1 {

		firstIntIdx = lastIntIdx
	}

	if isFractional && lastFracIdx == -1 {

		lastFracIdx = lenAbsIntRunes
	}

	numStrOut := ""

	if signVal < 0 {

		numStrOut = "-"
	}

	numStrOut += string(absAllRunes[firstIntIdx : lastIntIdx+1])

	if isFractional {

		numStrOut += string(numSeps.DecimalSeparator)

		numStrOut += string(absAllRunes[lastIntIdx+1 : lastFracIdx+1])
	}

	// nOutDto, err := nDto.ParseNumStr(numStrOut)
	nOutDto, err := new(numStrDtoQuark).parseNumStr(numSeps, numStrOut, ePrefix)

	if err != nil {

		return NumStrDto{},
			&FuncReturnError{
				ErrPrefix:  ePrefix.String(),
				ReturnFunc: "nOutDto, err := new(numStrDtoQuark).parseNumStr(numStrOut, numSeps, ePrefix)",
				ErrContext: fmt.Sprintf("numStrOut= '%v'", numStrOut),
				ErrMessage: err.Error(),
			}
	}

	return nOutDto, nil
}

// setPrecisionNumStrDto
//
//	Sets precision for the current NumStrDto instance.
//
//	'precision' identifies the number of decimal places to the
//	 right of the decimal point.
//
//	Input Parameters
//	================
//
//	numSeps                  NumericSeparatorDto
//	  Numeric Separators define the Decimal Separator character,
//	  Thousands Separator character, and Currency Symbol character.
//	  These separator characters serve two purposes. First they are
//	  used to format and display numeric values as number strings.
//	  Second, they are also used to parse number strings and
//	  convert them into numeric values.
//
//	  The input parameter 'nStrDto' will be configured with these
//	  Numeric Separators.
//
//	  If 'numSeps' Numeric Separators prove to be invalid, an error
//	  will be returned.
//
//	nStrDto                  *NumStrDto
//	  A pointer to an instance of NumStrDto. This object will be
//	  reconfigued with the 'precision' values generated by this
//	  method and the Numeric Separators passed by input parameter
//	  'numSeps'.
//
//	precision                uint
//	  The 'precision' values designates the number of places to the
//	  right of the decimal point which will be realized upon
//	  completion of this operation. The precision operation will be
//	  performed on the number string contained in the NumStrDto
//	  instance.
//
//	roundResult              bool
//	  If the 'precision' value is less than the current number of
//	  places to the right of the decimal point, this method will
//	  truncate the existing fractional digits. If 'roundResult' is
//	  set to 'true', this truncation operation will include
//	  rounding the last digit.
//
//	Return Parameters
//	=================
//
//	error
//	  If an error is encountered during processing, this returned
//	  error object will be configured with an appropriate error
//	  message.
func (nStrDtoMuon *numStrDtoMuon) setPrecisionNumStrDto(
	numSeps NumericSeparatorDto,
	nStrDto *NumStrDto,
	precision uint,
	roundResult bool,
	errPrefDto *ePref.ErrPrefixDto) error {

	var ePrefix *ePref.ErrPrefixDto
	var err error

	ePrefix,
		err = ePref.ErrPrefixDto{}.NewFromErrPrefDto(
		errPrefDto,
		"numStrDtoAtom.setNumericSeparatorsToDefaultIfEmpty()",
		"")

	if err != nil {
		return err
	}

	if nStrDto == nil {

		return &InputPtrNilError{
			ErrPrefix:     ePrefix.String(),
			ParameterName: "'nStrDto'",
		}
	}

	err = numSeps.IsValid(ePrefix.XCpy("Validating 'numSeps'").String())

	if err != nil {

		return &FuncReturnError{
			ErrPrefix:  ePrefix.String(),
			ReturnFunc: "err = numSeps.IsValid(ePrefix.XCpy(\"Validating 'numSeps'\").String())",
			ErrContext: "Error: Input parameter 'numSeps' is INVALID!\n" +
				"'numSeps' FAILED validation tests.",
			ErrMessage: err.Error(),
		}
	}

	nDtoNumStr, err := new(numStrDtoAtom).formatNumStr(
		nStrDto, false, LEADMINUSNEGVALFMTMODE, ePrefix)

	if err != nil {

		return &FuncReturnError{
			ErrPrefix: ePrefix.String(),
			ReturnFunc: "nDtoNumStr, err := new(numStrDtoAtom).formatNumStr(\n" +
				"  nDto, false, LEADMINUSNEGVALFMTMODE, ePrefix)",
			ErrContext: "",
			ErrMessage: err.Error(),
		}
	}

	n2, err := new(numStrDtoPhoton).setPrecision(
		numSeps, nDtoNumStr, precision, roundResult, ePrefix)

	if err != nil {

		return &FuncReturnError{
			ErrPrefix: ePrefix.String(),
			ReturnFunc: "n2, err := new(numStrDtoPhoton).setPrecision(\n" +
				"  numSeps, nDtoNumStr, precision, roundResult, ePrefix)",
			ErrContext: "",
			ErrMessage: err.Error(),
		}
	}

	err = new(numStrDtoMolecule).copy(nStrDto, &n2, true, ePrefix)

	if err != nil {
		return &FuncReturnError{
			ErrPrefix:  ePrefix.String(),
			ReturnFunc: "err = new(numStrDtoMolecule).copy(nStrDto, &n2, true, ePrefix)",
			ErrContext: "Error copying final result into NumStrDto instance 'nStrDto'.",
			ErrMessage: err.Error(),
		}
	}

	return nil
}
